### ISSUE TITLE
Julia v0.5

### ISSUE THREAD

**Issue by pevnak** [JuliaML/MLDataUtils.jl#12]
Have anyove tried to fix bugs with Julia v0.5
Test Summary:               | Pass  Error  Total
  tst_kfolds.jl             |    6      5     11
  KFolds constructor        |    3      1      4
  LabeledKFolds constructor |    3      1      4
  (Labeled)KFolds methods   |           1      1
  KFolds iterator           |           1      1
  LabeledKFolds iterator    |           1      1

**Comment by tbreloff** [comment]
The data iteration has been completely redesigned, but we haven't committed
to merging it yet. The 'tom' branch removes most of this functionality, and
the new api is temporarily living in StochasticOptimization.jl

**Comment by pevnak** [comment]
Thanks for the answer. If this functionality will be removed, what would be the package mostly used for? I will continue to rely on old MLBase, which provides such functionality. In the same time I do not think it is best idea to change these packages frequently, as it might drive people off the language.

**Comment by tbreloff** [comment]
If it wasn't clear, this is temporary. The new api is intended to replace
the old one.

As for not changing things... The reason I'm not pushing to master is
specifically to avoid api churn.

**Comment by Evizero** [comment]
absorbed by #13
