### ISSUE TITLE
Aim of this package

### ISSUE THREAD

**Issue by Evizero** [JuliaML/MLDataUtils.jl#2]
Hi JuliaML!

I took the liberty and pushed this little utility package directly to JuliaML. I initially created the code for my own presentations and tutorials in order to have some toy problems with which I could explain things like feature scaling and overfitting. Over time it mutated into this package.

So now I thought why not share it properly. It is already in a usable state and documented. I also plan to expand it with more algorithms for generating artificial regression and classification datasets.

I think this would be a good fit for the organization, but I can also move it to my account if some of you disagree.

Let me know what you think

**Comment by tbreloff** [comment]
Cool... I'm hoping you'll share your presentations/tutorials at some point too!

**Comment by Evizero** [comment]
@tbreloff I will at some point, but I really want to get them right first. I am working on a series of ML lecture notebooks whenever my time allows (my PhD supervisor is considering offering a class on ML using Julia for the exercises). Ideally I want to release those with accompanying videos on youtube. However, at this point I am still constantly rearranging and changing things, and am not really comfortable sharing the current messy state.
