### ISSUE TITLE
Scale to range

### ISSUE THREAD

**Issue by oxinabox** [JuliaML/MLDataUtils.jl#45]
We can scale to range,
e.g. `[0, 1]` or `[-1, 1]
in a similar way to how we znorm scale.

Where we fit the scaling factor on the training set, and use it on the testset.

I would like this,
and I will either implement it in my package, 
or PR it here.

**Comment by Evizero** [comment]
there is work on this here https://github.com/JuliaML/MLPreprocessing.jl

**Comment by oxinabox** [comment]
Ah right it is https://github.com/JuliaML/MLDataUtils.jl/issues/29
