### ISSUE TITLE
Absorb labelencoding from LearnBase and MLBase?

### ISSUE THREAD

**Issue by Evizero** [JuliaML/MLDataUtils.jl#5]
https://github.com/Evizero/LearnBase.jl#example

This seems like the best place to have utilities for labelencoding and decoding. This would really reduce the overhead in LearnBase, since its the only reason for it to require MLBase anyhow.

cc: @tbreloff

**Comment by tbreloff** [comment]
+100!

**Comment by Evizero** [comment]
Alright. I'll do that then and adapt the license accordingly
